### ISSUE TITLE
Southside should be to the right

### ISSUE THREAD

**Issue by ajgajg1134** [RamZallan/csh-map#4]
See title

**Comment by RamZallan** [comment]
The floormap was traced over the RIT floor plans, is there any reason besides preference as to why to flip it?

**Comment by ajgajg1134** [comment]
The only floorplan I'm aware of actually has southside pointing to the south https://www.rit.edu/fa/facilities/system/files/floorplans/1/043-3.pdf (RIT Login needed to view)

**Comment by RamZallan** [comment]
@ajgajg1134 Guess I was mistaken. Currently on mobile that's how it orients, I can look into styling it differently for different orientations.

**Comment by ajgajg1134** [comment]
TBH I don't actually care that much this issue is mostly a joke 👍
